export const LANDING = '/'
export const HOME = '/home'
export const LOGIN = '/login'
export const ADD_PET = '/add-pet'
export const SIGN_UP = '/signup'
export const ACCOUNT = '/account'
export const ADMIN = '/admin'
export const PASSWORD_FORGET = '/pswrd-forget'
